### ISSUE TITLE
error on repository methods find one entity by Id 

### ISSUE THREAD

**Issue by dimitridisko** [octante/MarvelAPIBundle#5]
Hi, I can't seem to get any repository classes (ComicsRepository, CreatorsRepository,...) to work as I'm expecting getComicById(intval($id)) to return the correct comic, but all i'm getting is a 404 Oo

https://github.com/dimitridisko/bubbles/blob/feature/replace-chadicus-with-octante/src/Front/AppBundle/Repository/ComicRepository.php

Retrieving more than one comic works all right using filters though

Hope I'm clear enough.

**Comment by octante** [comment]
Hi Dimitri,

yes, you are rightly. I'm fixing it, and tomorrow I will have a new release including your pull request.

Thank you very much!! :)

**Comment by octante** [comment]
Fix deployed, new release is available in packagist.

Thanks Dimitri!!

**Comment by dimitridisko** [comment]
thanks to you ! :D
